<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Machine [
<!ELEMENT Machine (PunctChar*, Field*, FileChannel*, Register*, RegisterArray*, ConditionBit*, RAM*, Set*, Test*, Increment*, Shift*, Logical*, Arithmetic*, Branch*, TransferRtoR*, TransferRtoA*, TransferAtoR*, Decode*, SetCondBit*, IO*, MemoryAccess*, End, Comment*, EQU*, FetchSequence, MachineInstruction*, HighlightingInfo?, LoadingInfo?, ModuleWindowsInfo?) >
<!ATTLIST Machine name CDATA "unnamed">
<!ELEMENT PunctChar EMPTY>
<!ATTLIST PunctChar char CDATA #REQUIRED use  (symbol|token|label|comment|pseudo|illegal) #REQUIRED>
<!ELEMENT Field (FieldValue*)>
<!ATTLIST Field name CDATA #REQUIRED type  (required|optional|ignored) #REQUIRED numBits CDATA #REQUIRED relativity (absolute|pcRelativePreIncr|pcRelativePostIncr) #REQUIRED defaultValue CDATA #REQUIRED signed (true|false) #REQUIRED offset CDATA #REQUIRED id ID #REQUIRED>
<!ELEMENT FieldValue EMPTY>
<!ATTLIST FieldValue name CDATA #REQUIRED value CDATA #REQUIRED>
<!ELEMENT FileChannel EMPTY>
<!ATTLIST FileChannel file CDATA #REQUIRED id ID #REQUIRED>
<!ELEMENT Register EMPTY>
<!ATTLIST Register name CDATA #REQUIRED width CDATA #REQUIRED id ID #REQUIRED>
<!ELEMENT RegisterArray (Register+)>
<!ATTLIST RegisterArray name CDATA #REQUIRED width CDATA #REQUIRED length CDATA #REQUIRED id ID #REQUIRED>
<!ELEMENT ConditionBit EMPTY>
<!ATTLIST ConditionBit name CDATA #REQUIRED bit CDATA #REQUIRED register IDREF #REQUIRED halt (true|false) "false" id ID #REQUIRED>
<!ELEMENT RAM EMPTY>
<!ATTLIST RAM name CDATA #REQUIRED length CDATA #REQUIRED id ID #REQUIRED cellSize CDATA "8">
<!ELEMENT Increment EMPTY>
<!ATTLIST Increment name CDATA #REQUIRED register IDREF #REQUIRED overflowBit IDREF #IMPLIED delta CDATA #REQUIRED id ID #REQUIRED>
<!ELEMENT Arithmetic EMPTY>
<!ATTLIST Arithmetic name CDATA #REQUIRED type (ADD|SUBTRACT|MULTIPLY|DIVIDE) #REQUIRED source1 IDREF #REQUIRED source2 IDREF #REQUIRED destination IDREF #REQUIRED overflowBit IDREF #IMPLIED  carryBit IDREF #IMPLIED  id ID #REQUIRED>
<!ELEMENT TransferRtoR EMPTY>
<!ATTLIST TransferRtoR name CDATA #REQUIRED source IDREF #REQUIRED srcStartBit CDATA #REQUIRED dest IDREF #REQUIRED destStartBit CDATA #REQUIRED numBits CDATA #REQUIRED id ID #REQUIRED>
<!ELEMENT TransferRtoA EMPTY>
<!ATTLIST TransferRtoA name CDATA #REQUIRED source IDREF #REQUIRED srcStartBit CDATA #REQUIRED dest IDREF #REQUIRED destStartBit CDATA #REQUIRED numBits CDATA #REQUIRED index IDREF #REQUIRED indexStart CDATA #IMPLIED indexNumBits CDATA #IMPLIED id ID #REQUIRED>
<!ELEMENT TransferAtoR EMPTY>
<!ATTLIST TransferAtoR name CDATA #REQUIRED source IDREF #REQUIRED srcStartBit CDATA #REQUIRED dest IDREF #REQUIRED destStartBit CDATA #REQUIRED numBits CDATA #REQUIRED index IDREF #REQUIRED indexStart CDATA #IMPLIED indexNumBits CDATA #IMPLIED id ID #REQUIRED>
<!ELEMENT Shift EMPTY>
<!ATTLIST Shift name CDATA #REQUIRED source IDREF #REQUIRED destination IDREF #REQUIRED type (logical | arithmetic | cyclic) #REQUIRED direction (right | left) #REQUIRED distance CDATA #REQUIRED id ID #REQUIRED>
<!ELEMENT Branch EMPTY>
<!ATTLIST Branch name CDATA #REQUIRED amount CDATA #REQUIRED id ID #REQUIRED>
<!ELEMENT Logical EMPTY>
<!ATTLIST Logical name CDATA #REQUIRED source1 IDREF #REQUIRED source2 IDREF #REQUIRED destination IDREF #REQUIRED type (AND | OR | NAND | NOR | XOR | NOT) #REQUIRED id ID #REQUIRED>
<!ELEMENT Set EMPTY>
<!ATTLIST Set name CDATA #REQUIRED register IDREF #REQUIRED start CDATA #REQUIRED numBits CDATA #REQUIRED value CDATA #REQUIRED id ID #REQUIRED>
<!ELEMENT Test EMPTY >
<!ATTLIST Test name CDATA #REQUIRED register IDREF #REQUIRED start CDATA #REQUIRED numBits CDATA #REQUIRED comparison (EQ | NE | LT | GT | LE | GE ) #REQUIRED value CDATA #REQUIRED omission CDATA #REQUIRED id ID #REQUIRED>
<!ELEMENT Decode EMPTY >
<!ATTLIST Decode name CDATA #REQUIRED ir IDREF #REQUIRED id ID #REQUIRED>
<!ELEMENT IO EMPTY >
<!ATTLIST IO name CDATA #REQUIRED direction (input | output) #REQUIRED type (integer | ascii | unicode) #REQUIRED buffer IDREF #REQUIRED connection CDATA #IMPLIED id ID #REQUIRED>
<!ELEMENT MemoryAccess EMPTY >
<!ATTLIST MemoryAccess name CDATA #REQUIRED direction (read | write ) #REQUIRED memory IDREF #REQUIRED data IDREF #REQUIRED address IDREF #REQUIRED id ID #REQUIRED>
<!ELEMENT SetCondBit EMPTY >
<!ATTLIST SetCondBit name CDATA #REQUIRED bit IDREF #REQUIRED value (0 | 1) #REQUIRED id ID #REQUIRED>
<!ELEMENT End EMPTY>
<!ATTLIST End id ID #REQUIRED>
<!ELEMENT Comment EMPTY>
<!ATTLIST Comment name CDATA #REQUIRED id ID #REQUIRED>
<!ELEMENT Microinstruction EMPTY>
<!ATTLIST Microinstruction microRef IDREF #REQUIRED>
<!ELEMENT MachineInstruction (Microinstruction*)>
<!ATTLIST MachineInstruction name CDATA #REQUIRED opcode CDATA #REQUIRED format CDATA #REQUIRED>
<!ELEMENT FetchSequence (Microinstruction*) >
<!ELEMENT EQU EMPTY>
<!ATTLIST EQU name CDATA #REQUIRED value CDATA #REQUIRED>
<!ELEMENT HighlightingInfo (RegisterRAMPair*)>
<!ELEMENT RegisterRAMPair EMPTY>
<!ATTLIST RegisterRAMPair register IDREF #REQUIRED ram IDREF #REQUIRED dynamic (true|false) #REQUIRED>
<!ELEMENT LoadingInfo EMPTY>
<!ATTLIST LoadingInfo ram IDREF #IMPLIED startingAddress CDATA "0">
<!ELEMENT ModuleWindowsInfo ((RegisterWindowInfo | RegisterArrayWindowInfo | RAMWindowInfo)*) >
<!ELEMENT RegisterWindowInfo EMPTY>
<!ATTLIST RegisterWindowInfo top CDATA "50" left CDATA "50" width CDATA "300" height CDATA "150" base (Decimal|Binary|Hexadecimal|Ascii|UnsignedDec|Unicode)  "Decimal">
<!ELEMENT RegisterArrayWindowInfo EMPTY>
<!ATTLIST RegisterArrayWindowInfo array IDREF #REQUIRED top CDATA "50" left CDATA "50" width CDATA "300" height CDATA "150" base (Decimal|Binary|Hexadecimal|Ascii|UnsignedDec|Unicode) "Decimal">
<!ELEMENT RAMWindowInfo EMPTY>
<!ATTLIST RAMWindowInfo ram IDREF #REQUIRED cellSize CDATA "1" top CDATA "50" left CDATA "50" width CDATA "450" height CDATA "450" contentsbase (Decimal|Binary|Hexadecimal|Ascii|UnsignedDec|Unicode) "Decimal" addressbase (Decimal|Binary|Hexadecimal) "Decimal">
]>

<Machine name="anmol" >
	<!--............. Punctuation Options .............-->
	<PunctChar char="!" use="symbol" />
	<PunctChar char="#" use="symbol" />
	<PunctChar char="$" use="symbol" />
	<PunctChar char="%" use="symbol" />
	<PunctChar char="&amp;" use="symbol" />
	<PunctChar char="^" use="symbol" />
	<PunctChar char="_" use="symbol" />
	<PunctChar char="`" use="symbol" />
	<PunctChar char="*" use="symbol" />
	<PunctChar char="?" use="symbol" />
	<PunctChar char="@" use="symbol" />
	<PunctChar char="~" use="symbol" />
	<PunctChar char="+" use="symbol" />
	<PunctChar char="-" use="symbol" />
	<PunctChar char="(" use="token" />
	<PunctChar char=")" use="token" />
	<PunctChar char="," use="token" />
	<PunctChar char="/" use="token" />
	<PunctChar char="=" use="token" />
	<PunctChar char="[" use="token" />
	<PunctChar char="\" use="token" />
	<PunctChar char="]" use="token" />
	<PunctChar char="{" use="token" />
	<PunctChar char="|" use="token" />
	<PunctChar char="}" use="token" />
	<PunctChar char="." use="pseudo" />
	<PunctChar char=":" use="label" />
	<PunctChar char=";" use="comment" />

	<!--......... machine instruction fields ............-->
	<Field name="ADDR" type="required" numBits="12" relativity="absolute" signed="true" offset="0" defaultValue="0" id="Field143204">
	</Field>
	<Field name="OPCODE" type="required" numBits="4" relativity="absolute" signed="true" offset="0" defaultValue="0" id="Fieldf4ea87">
	</Field>
	<Field name="OPERATION" type="required" numBits="16" relativity="absolute" signed="true" offset="0" defaultValue="0" id="Field6f132d">
	</Field>

	<!--............. FileChannels .................-->
	<!-- none -->

	<!--............. registers .....................-->
	<Register name="AC" width="16" id="module.Register1316f03" />
	<Register name="AR" width="12" id="module.Register9c1981" />
	<Register name="DR" width="16" id="module.Register1dda971" />
	<Register name="E" width="1" id="module.Register11080cc" />
	<Register name="FGI" width="1" id="module.Register139b21a" />
	<Register name="FGO" width="1" id="module.Register11df32d" />
	<Register name="I" width="1" id="module.Register17b4a5e" />
	<Register name="INPR" width="8" id="module.Register8cac5d" />
	<Register name="IR" width="16" id="module.Registered6b34" />
	<Register name="OUTR" width="8" id="module.Register185f4a5" />
	<Register name="PC" width="12" id="module.Register6e530c" />
	<Register name="S" width="1" id="module.Register11921fe" />
	<Register name="TR" width="16" id="module.Register6f569b" />

	<!--............. register arrays ...............-->
	<!-- none -->

	<!--............. condition bits ................-->
	<ConditionBit name="HALT-BIT" bit="0" register="module.Register11921fe" halt="true" id="module.ConditionBitdae2f" />

	<!--............. rams ..........................-->
	<RAM name="MAIN MEMORY" length="4096" cellSize="16" id="module.RAMe16791" />

	<!--............. set ...........................-->
	<Set name="AC &lt;- 0" register="module.Register1316f03" start="0" numBits="16" value="0" id="microinstruction.CpusimSet1675b1e" />
	<Set name="E &lt;- 0" register="module.Register11080cc" start="0" numBits="1" value="0" id="microinstruction.CpusimSetcf604c" />

	<!--............. test ..........................-->
	<Test name="SNA" register="module.Register1316f03" start="0" numBits="1" comparison="EQ" value="1" omission="1" id="microinstruction.Test1903608" />
	<Test name="SPA" register="module.Register1316f03" start="0" numBits="1" comparison="EQ" value="0" omission="1" id="microinstruction.Test9a2b8e" />
	<Test name="SZA" register="module.Register1316f03" start="0" numBits="16" comparison="EQ" value="0" omission="1" id="microinstruction.Test1563468" />
	<Test name="SZE" register="module.Register11080cc" start="0" numBits="1" comparison="EQ" value="0" omission="1" id="microinstruction.Testdcfc0e" />
	<Test name="TEST_DR" register="module.Register1dda971" start="0" numBits="16" comparison="EQ" value="0" omission="1" id="microinstruction.Test1c0beca" />

	<!--............. increment .....................-->
	<Increment name="AC &lt;-  AC +1" register="module.Register1316f03" overflowBit="module.ConditionBitdae2f" delta="1" id="microinstruction.Incrementf0a7ab" />
	<Increment name="AR &lt;- AR + 1" register="module.Register9c1981" overflowBit="module.ConditionBitdae2f" delta="1" id="microinstruction.Increment187768d" />
	<Increment name="DR &lt;- DR + 1" register="module.Register1dda971" overflowBit="module.ConditionBitdae2f" delta="1" id="microinstruction.Incrementc23d2c" />
	<Increment name="PC &lt;- PC +1" register="module.Register6e530c" overflowBit="module.ConditionBitdae2f" delta="1" id="microinstruction.Increment1bd3620" />

	<!--............. shift .........................-->
	<Shift name="AC &lt;- shr AC(left)" type="cyclic" source="module.Register1316f03" destination="module.Register1316f03" direction="left" distance="1" id="microinstruction.Shift14f39eb" />
	<Shift name="AC &lt;- shr AC(right)" type="cyclic" source="module.Register1316f03" destination="module.Register1316f03" direction="right" distance="1" id="microinstruction.Shift1430014" />

	<!--............. logical .......................-->
	<Logical name="AC &lt;- AC'" type="NOT" source1="module.Register1316f03" source2="module.Register1316f03" destination="module.Register1316f03" id="microinstruction.Logical1c1c6b2" />
	<Logical name="AC &lt;- AC^DR" type="AND" source1="module.Register1316f03" source2="module.Register1dda971" destination="module.Register1316f03" id="microinstruction.Logicalba96bb" />
	<Logical name="E &lt;- E'" type="NOT" source1="module.Register11080cc" source2="module.Register11080cc" destination="module.Register11080cc" id="microinstruction.Logical852ebe" />

	<!--............. arithmetic ....................-->
	<Arithmetic name="AC &lt;- AC + DR" type="ADD" source1="module.Register1316f03" source2="module.Register1dda971" destination="module.Register1316f03" overflowBit="module.ConditionBitdae2f" carryBit="module.ConditionBitdae2f" id="microinstruction.Arithmeticb71026" />

	<!--............. branch ........................-->
	<!-- none -->

	<!--............. transferRtoR ..................-->
	<TransferRtoR name=" E &lt;- AC(0)" source="module.Register1316f03" srcStartBit="0" dest="module.Register11080cc" destStartBit="0" numBits="1" id="microinstruction.TransferRtoR6ac3b2" />
	<TransferRtoR name="AC &lt;- DR" source="module.Register1dda971" srcStartBit="0" dest="module.Register1316f03" destStartBit="0" numBits="16" id="microinstruction.TransferRtoR149d29b" />
	<TransferRtoR name="AC(0) &lt;- E" source="module.Register11080cc" srcStartBit="0" dest="module.Register1316f03" destStartBit="0" numBits="1" id="microinstruction.TransferRtoR4d2763" />
	<TransferRtoR name="AC(15) &lt;- E" source="module.Register11080cc" srcStartBit="0" dest="module.Register1316f03" destStartBit="15" numBits="1" id="microinstruction.TransferRtoR1ea848e" />
	<TransferRtoR name="AR &lt;- IR(0-11)" source="module.Registered6b34" srcStartBit="4" dest="module.Register9c1981" destStartBit="0" numBits="12" id="microinstruction.TransferRtoR69a193" />
	<TransferRtoR name="AR &lt;-PC" source="module.Register6e530c" srcStartBit="0" dest="module.Register9c1981" destStartBit="0" numBits="12" id="microinstruction.TransferRtoR42807f" />
	<TransferRtoR name="E &lt;- AC(15)" source="module.Register1316f03" srcStartBit="15" dest="module.Register11080cc" destStartBit="0" numBits="1" id="microinstruction.TransferRtoR155c7ab" />
	<TransferRtoR name="I &lt;- IR(15)" source="module.Registered6b34" srcStartBit="15" dest="module.Register17b4a5e" destStartBit="0" numBits="1" id="microinstruction.TransferRtoR94ff7b" />
	<TransferRtoR name="PC &lt;- AR" source="module.Register9c1981" srcStartBit="0" dest="module.Register6e530c" destStartBit="0" numBits="12" id="microinstruction.TransferRtoR19ccc08" />

	<!--............. transferRtoA ..................-->
	<!-- none -->

	<!--............. transferAtoR ..................-->
	<!-- none -->

	<!--............. decode ........................-->
	<Decode name="DECODE_IR" ir="module.Registered6b34" id="microinstruction.Decode194a083" />

	<!--............. set condition bit .............-->
	<SetCondBit name="HLT &lt;- 1" bit="module.ConditionBitdae2f" value="1" id="microinstruction.SetCondBit1b59676" />

	<!--............. io ............................-->
	<!-- none -->

	<!--............. memory access .................-->
	<MemoryAccess name="DR &lt;- M[AR]" direction="read" memory="module.RAMe16791" data="module.Register1dda971" address="module.Register9c1981" id="microinstruction.MemoryAccessb11ff1" />
	<MemoryAccess name="IR &lt;- M[AR]" direction="read" memory="module.RAMe16791" data="module.Registered6b34" address="module.Register9c1981" id="microinstruction.MemoryAccess6662b4" />
	<MemoryAccess name="M[AR] &lt;- AC" direction="write" memory="module.RAMe16791" data="module.Register1316f03" address="module.Register9c1981" id="microinstruction.MemoryAccess1324b43" />
	<MemoryAccess name="M[AR] &lt;- DR" direction="write" memory="module.RAMe16791" data="module.Register1dda971" address="module.Register9c1981" id="microinstruction.MemoryAccess9266b9" />
	<MemoryAccess name="M[AR] &lt;- PC" direction="write" memory="module.RAMe16791" data="module.Register6e530c" address="module.Register9c1981" id="microinstruction.MemoryAccess645b9b" />

	<!--............. end ...........................-->
	<End id="microinstruction.End1b43e64" />

	<!--............. comment ...........................-->
	<!-- none -->

	<!--............. global equs ..................-->
	<!-- none -->

	<!--............. fetch sequence ................-->
	<FetchSequence>
		<Microinstruction microRef="microinstruction.TransferRtoR42807f" />
		<Microinstruction microRef="microinstruction.MemoryAccess6662b4" />
		<Microinstruction microRef="microinstruction.Increment1bd3620" />
		<Microinstruction microRef="microinstruction.TransferRtoR69a193" />
		<Microinstruction microRef="microinstruction.TransferRtoR94ff7b" />
		<Microinstruction microRef="microinstruction.Decode194a083" />
		<Microinstruction microRef="microinstruction.End1b43e64" />
	</FetchSequence>

	<!--............. machine instructions ..........-->

	<MachineInstruction name="ISZ" opcode="6" format="OPCODE ADDR" >
		<Microinstruction microRef="microinstruction.MemoryAccessb11ff1" />
		<Microinstruction microRef="microinstruction.Incrementc23d2c" />
		<Microinstruction microRef="microinstruction.MemoryAccess9266b9" />
		<Microinstruction microRef="microinstruction.Test1c0beca" />
		<Microinstruction microRef="microinstruction.End1b43e64" />
		<Microinstruction microRef="microinstruction.Increment1bd3620" />
		<Microinstruction microRef="microinstruction.End1b43e64" />
	</MachineInstruction>

	<MachineInstruction name="BSA" opcode="5" format="OPCODE ADDR" >
		<Microinstruction microRef="microinstruction.MemoryAccess645b9b" />
		<Microinstruction microRef="microinstruction.Increment187768d" />
		<Microinstruction microRef="microinstruction.TransferRtoR19ccc08" />
		<Microinstruction microRef="microinstruction.End1b43e64" />
	</MachineInstruction>

	<MachineInstruction name="BUN" opcode="4" format="OPCODE ADDR" >
		<Microinstruction microRef="microinstruction.TransferRtoR19ccc08" />
		<Microinstruction microRef="microinstruction.MemoryAccessb11ff1" />
		<Microinstruction microRef="microinstruction.End1b43e64" />
	</MachineInstruction>

	<MachineInstruction name="STA" opcode="3" format="OPCODE ADDR" >
		<Microinstruction microRef="microinstruction.MemoryAccessb11ff1" />
		<Microinstruction microRef="microinstruction.MemoryAccess1324b43" />
		<Microinstruction microRef="microinstruction.End1b43e64" />
	</MachineInstruction>

	<MachineInstruction name="LDA" opcode="2" format="OPCODE ADDR" >
		<Microinstruction microRef="microinstruction.MemoryAccessb11ff1" />
		<Microinstruction microRef="microinstruction.TransferRtoR149d29b" />
		<Microinstruction microRef="microinstruction.End1b43e64" />
	</MachineInstruction>

	<MachineInstruction name="ADD" opcode="1" format="OPCODE ADDR" >
		<Microinstruction microRef="microinstruction.MemoryAccessb11ff1" />
		<Microinstruction microRef="microinstruction.Arithmeticb71026" />
		<Microinstruction microRef="microinstruction.End1b43e64" />
	</MachineInstruction>

	<MachineInstruction name="AND" opcode="0" format="OPCODE ADDR" >
		<Microinstruction microRef="microinstruction.MemoryAccessb11ff1" />
		<Microinstruction microRef="microinstruction.Logicalba96bb" />
		<Microinstruction microRef="microinstruction.End1b43e64" />
	</MachineInstruction>

	<MachineInstruction name="ISZ_I" opcode="e" format="OPCODE ADDR" >
	</MachineInstruction>

	<MachineInstruction name="BSA_I" opcode="d" format="OPCODE ADDR" >
	</MachineInstruction>

	<MachineInstruction name="BUN_I" opcode="c" format="OPCODE ADDR" >
	</MachineInstruction>

	<MachineInstruction name="STA_I" opcode="b" format="OPCODE ADDR" >
	</MachineInstruction>

	<MachineInstruction name="LDA_I" opcode="a" format="OPCODE ADDR" >
	</MachineInstruction>

	<MachineInstruction name="AND_I" opcode="8" format="OPCODE ADDR" >
	</MachineInstruction>

	<MachineInstruction name="ADD_I" opcode="9" format="OPCODE ADDR" >
	</MachineInstruction>

	<MachineInstruction name="HLT" opcode="7001" format="OPERATION" >
		<Microinstruction microRef="microinstruction.SetCondBit1b59676" />
		<Microinstruction microRef="microinstruction.End1b43e64" />
	</MachineInstruction>

	<MachineInstruction name="SZE" opcode="7002" format="OPERATION" >
		<Microinstruction microRef="microinstruction.Testdcfc0e" />
		<Microinstruction microRef="microinstruction.End1b43e64" />
		<Microinstruction microRef="microinstruction.Increment1bd3620" />
		<Microinstruction microRef="microinstruction.End1b43e64" />
	</MachineInstruction>

	<MachineInstruction name="SZA" opcode="7004" format="OPERATION" >
		<Microinstruction microRef="microinstruction.Test1563468" />
		<Microinstruction microRef="microinstruction.End1b43e64" />
		<Microinstruction microRef="microinstruction.Increment1bd3620" />
		<Microinstruction microRef="microinstruction.End1b43e64" />
	</MachineInstruction>

	<MachineInstruction name="SNA" opcode="7008" format="OPERATION" >
		<Microinstruction microRef="microinstruction.Test1903608" />
		<Microinstruction microRef="microinstruction.End1b43e64" />
		<Microinstruction microRef="microinstruction.Increment1bd3620" />
		<Microinstruction microRef="microinstruction.End1b43e64" />
	</MachineInstruction>

	<MachineInstruction name="SPA" opcode="7010" format="OPERATION" >
		<Microinstruction microRef="microinstruction.Test9a2b8e" />
		<Microinstruction microRef="microinstruction.End1b43e64" />
		<Microinstruction microRef="microinstruction.Increment1bd3620" />
		<Microinstruction microRef="microinstruction.End1b43e64" />
	</MachineInstruction>

	<MachineInstruction name="INC" opcode="7020" format="OPERATION" >
		<Microinstruction microRef="microinstruction.Incrementf0a7ab" />
		<Microinstruction microRef="microinstruction.End1b43e64" />
	</MachineInstruction>

	<MachineInstruction name="CIL" opcode="7040" format="OPERATION" >
		<Microinstruction microRef="microinstruction.TransferRtoR4d2763" />
		<Microinstruction microRef="microinstruction.Shift14f39eb" />
		<Microinstruction microRef="microinstruction.TransferRtoR155c7ab" />
		<Microinstruction microRef="microinstruction.End1b43e64" />
		<Microinstruction microRef="microinstruction.TransferRtoR6ac3b2" />
	</MachineInstruction>

	<MachineInstruction name="CIR" opcode="7080" format="OPERATION" >
		<Microinstruction microRef="microinstruction.Shift1430014" />
		<Microinstruction microRef="microinstruction.TransferRtoR1ea848e" />
		<Microinstruction microRef="microinstruction.TransferRtoR6ac3b2" />
		<Microinstruction microRef="microinstruction.End1b43e64" />
	</MachineInstruction>

	<MachineInstruction name="CME" opcode="7100" format="OPERATION" >
		<Microinstruction microRef="microinstruction.Logical852ebe" />
		<Microinstruction microRef="microinstruction.End1b43e64" />
	</MachineInstruction>

	<MachineInstruction name="CMA" opcode="7200" format="OPERATION" >
		<Microinstruction microRef="microinstruction.Logical1c1c6b2" />
		<Microinstruction microRef="microinstruction.End1b43e64" />
	</MachineInstruction>

	<MachineInstruction name="CLE" opcode="7400" format="OPERATION" >
		<Microinstruction microRef="microinstruction.CpusimSetcf604c" />
		<Microinstruction microRef="microinstruction.End1b43e64" />
	</MachineInstruction>

	<MachineInstruction name="CLA" opcode="7800" format="OPERATION" >
		<Microinstruction microRef="microinstruction.CpusimSet1675b1e" />
		<Microinstruction microRef="microinstruction.End1b43e64" />
	</MachineInstruction>

	<!--............. highlighting info .............-->
	<HighlightingInfo>
	</HighlightingInfo>

	<!--............. loading info ..................-->
	<LoadingInfo ram="module.RAMe16791" startingAddress="34" />

	<!--............. module window info ............-->
	<ModuleWindowsInfo>
		<RAMWindowInfo ram="module.RAMe16791" cellSize="1" contentsbase="Hexadecimal" addressbase="Hexadecimal" 
			top="64" left="889" width="415" height="440" />
		<RegisterWindowInfo base="Hexadecimal" 
			top="30" left="8" width="355" height="313" />
	</ModuleWindowsInfo>

</Machine>
